apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetflow
  labels:
    app: budgetflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budgetflow
  template:
    metadata:
      labels:
        app: budgetflow
    spec:
      containers:
      - name: budgetflow
        image: francisolu26/budgetflow-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"