apiVersion: v1
kind: Service
metadata:
  name: budgetflow-service
spec:
  selector:
    app: budgetflow
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080