[webserver]
budgetflow ansible_host=54.154.184.142 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/webserver/budget_app/terraform/budgetflow-key.pem

[webserver:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
